=== jibx/schema-library/org.opentravel/x2010B/opentravel-schema/schema/src/main/schema/ota-schema/OTA_AirFlifoRS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.opentravel.org/OTA/2003/05" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentravel.org/OTA/2003/05" elementFormDefault="qualified" version="3.000" id="OTA2010B">
  <xs:include schemaLocation="OTA_AirCommonTypes.xsd"/>
  <xs:annotation>
    <xs:documentation xml:lang="en">All Schema files in the OpenTravel Alliance specification are made available according to the terms defined by the OpenTravel License Agreement at http://www.opentravel.org/Specifications/Default.aspx.</xs:documentation>
  </xs:annotation>
  <xs:element name="OTA_AirFlifoRS">
    <xs:annotation>
      <xs:documentation xml:lang="en">Details of flight departure, arrival and gate information for a particular flight, including actual as well as scheduled departure and arrival times.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice>
        <xs:sequence>
          <xs:element name="Success" type="SuccessType">
            <xs:annotation>
              <xs:documentation xml:lang="en"> Standard way to indicate successful processing of an OpenTravel message. Returning an empty element of this type indicates success.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Warnings" type="WarningsType" minOccurs="0">
            <xs:annotation>
              <xs:documentation xml:lang="en">Standard way to indicate successful processing of an OpenTravel message, but one in which warnings are generated.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="FlightInfoDetails" minOccurs="0" maxOccurs="100">
            <xs:annotation>
              <xs:documentation xml:lang="en">A collection of flight information for a flight number.</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="FlightLegInfo" maxOccurs="10">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">Information regarding each leg of the flight. A flight leg is one departure and one arrival (non-stop sector).</xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="DepartureAirport" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">Departure airport for flight leg.</xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="Comment" type="FreeTextType" minOccurs="0" maxOccurs="unbounded">
                              <xs:annotation>
                                <xs:documentation xml:lang="en">Any special comments about the departure airport.</xs:documentation>
                              </xs:annotation>
                            </xs:element>
                          </xs:sequence>
                          <xs:attributeGroup ref="AirportLocationGroup"/>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="ArrivalAirport" minOccurs="0" maxOccurs="2">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">Arrival point of flight segment. Second occurrence indicates diversion airport.</xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="Comment" type="FreeTextType" minOccurs="0" maxOccurs="unbounded">
                              <xs:annotation>
                                <xs:documentation xml:lang="en">Any special comments about the arrival airport.</xs:documentation>
                              </xs:annotation>
                            </xs:element>
                          </xs:sequence>
                          <xs:attributeGroup ref="AirportLocationGroup"/>
                          <xs:attribute name="Diversion" type="xs:boolean" use="required">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Indicates the flight has diverted to this airport.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="BaggageClaim" type="StringLength1to8" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Specifies the location or carousel number for baggage from the arriving flight.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="MarketingAirline" type="CompanyNameType">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">The marketing airline.</xs:documentation>
                        </xs:annotation>
                      </xs:element>
                      <xs:element name="OperatingAirline" type="OperatingAirlineType" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">The operating airline of the flight if it is a codeshare  flight.</xs:documentation>
                        </xs:annotation>
                      </xs:element>
                      <xs:element name="Equipment" type="EquipmentType" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">The type of equipment  used for the  flight.</xs:documentation>
                        </xs:annotation>
                      </xs:element>
                      <xs:element name="Comment" minOccurs="0" maxOccurs="5">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">Any special comments on the leg such as travel advisory messages, passenger advisory messages, etc.</xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="FreeTextType"/>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="DepartureDateTime" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">Specifies scheduled and other  date time information.</xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:attribute name="Scheduled" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Scheduled departure date/time for flight leg.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="Estimated" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Estimated departure date/time for flight leg.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="Actual" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Actual operational departure date/time for flight leg.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="ReasonCode" type="OTA_CodeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">The reason attributed to a delay or cancellation. Refers to OpenTravel Code Table Flight Delay Code (FDC).</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="NextAdvisoryTime" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Specifies the time when the next information will be published.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="ArrivalDateTime" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation xml:lang="en">Specifies scheduled and other date time information.</xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:attribute name="Scheduled" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Scheduled arrival date/time for flight leg.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="Estimated" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Estimated arrival date/time for flight leg.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="Actual" type="TimeOrDateTimeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">Actual operational arrival date/time for flight leg.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                          <xs:attribute name="ReasonCode" type="OTA_CodeType" use="optional">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">The reason attributed to a delay or cancellation. Refers to OpenTravel Code Table Flight Delay Code (FDC).</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="OperationTimes" minOccurs="0">
                        <xs:annotation>
                          <xs:documentation xml:lang="en"> A collection of OperationTimes.</xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="OperationTime" maxOccurs="99">
                              <xs:annotation>
                                <xs:documentation xml:lang="en">Provides information on operational events for this flight leg e.g. off-ground.</xs:documentation>
                              </xs:annotation>
                              <xs:complexType>
                                <xs:attributeGroup ref="OperationTimeGroup"/>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                    <xs:attributeGroup ref="FlifoLegAttributes"/>
                    <xs:attribute name="FlightStatus" type="StringLength1to32" use="optional">
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Status of the current flight operation.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="OnTimeRate" type="Percentage" use="optional">
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Specifies the Department of Transportation on time rate for the flight leg.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                  </xs:complexType>
                </xs:element>
                <xs:element name="Comment" type="FreeTextType" minOccurs="0" maxOccurs="5">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">Any special comments on the flight.</xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element name="Warnings" type="WarningsType" minOccurs="0">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">Warning(s) specifying an application error  for this flight (e.g., invalid flight number).</xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
              <xs:attribute name="MessageStatus" type="StringLength1to32" use="optional">
                <xs:annotation>
                  <xs:documentation xml:lang="en">Indicates various status information about the flight such as real-time, scheduled or flight cancelled.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attributeGroup ref="AirDetailsRSAttributes"/>
              <xs:attribute name="FlightNumber" type="FlightNumberType" use="optional">
                <xs:annotation>
                  <xs:documentation xml:lang="en">The flight number of the flight.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:element name="Errors" type="ErrorsType">
          <xs:annotation>
            <xs:documentation xml:lang="en">A collection of errors that occurred during the processing of a message.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
      <xs:attributeGroup ref="OTA_PayloadStdAttributes">
        <xs:annotation>
          <xs:documentation xml:lang="en">The OTA_PayloadStdAttributes defines the standard attributes that appear on the root element for all OpenTravel messages.</xs:documentation>
        </xs:annotation>
      </xs:attributeGroup>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jibx/schema-library/org.opentravel/2011A/opentravel-schema/schema/src/main/schema/ota-schema/OTA_AirFlifoRS2.xml
<?xml version="1.0" encoding="UTF-8"?><OTA_AirFlifoRS EchoToken="566732" TimeStamp="2003-03-17T09:30:47-05:00" Target="Production" Version="1.002" SequenceNmbr="1" xmlns="http://www.opentravel.org/OTA/2003/05" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opentravel.org/OTA/2003/05OTA_AirFlifoRS.xsd">	<Success/>	<FlightInfoDetails TotalFlightTime="PT2H38M" TotalMiles="907">		<FlightLegInfo FlightNumber="1716" JourneyDuration="PT2H38M" LegDistance="907">			<DepartureAirport LocationCode="ATL"/>			<ArrivalAirport LocationCode="MSP" Diversion="0"/>			<MarketingAirline CompanyShortName="Delta" Code="DL">Delta Airlines</MarketingAirline>			<Equipment AirEquipType="738">Boeing 737-800</Equipment>			<DepartureDateTime Scheduled="2003-04-15T08:05:00"/>			<ArrivalDateTime Scheduled="2003-04-15T09:43:00" Estimated="2003-04-15T09:43:00"/>		</FlightLegInfo>	</FlightInfoDetails></OTA_AirFlifoRS>
